env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules:
  'vue/html-self-closing': ['error', { 'html': { 'void': 'always' } }]
  'vue/max-attributes-per-line': ['error', { 'singleline': { 'max': 3 }, 'multiline': { 'max': 2 } }]
  'vue/no-v-html': off #ユーザーからの入力欄はなく、XSSの危険はないのでoffに設定
  '@typescript-eslint/no-unused-vars': off
